version: "3"

services:
  errbit:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - PORT=8080
      - RACK_ENV=production
      - MONGO_URL=mongodb://mongo:27017/errbit
      - SECRET_KEY_BASE=my$ecre7key123
  mongo:
    image: mongo:4.1
    ports:
      - "27017"
